site_name: AI-Enhanced Documentation Generator
site_description: Auto-generate clean, AI-enhanced docs for any codebase
theme:
  name: material
  language: en
  logo: images/robot.svg
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>/AI-Enhanced-Documentation-Generator
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/<your-linkedin>
nav:
  - Home: index.md
  - API Reference: api.md
extra_css:
  - extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - tables
